version: "3.8"

services:
  nuxt:
    restart: on-failure
    build: .
    command: yarn start
    networks:
      - app_network

  nginx:
    restart: on-failure
    build: ./.nginx
    container_name: rguide_frontend
    depends_on:
      - nuxt
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
  server:
    external: true
